language: android
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_e7ac0b1660ba_key -iv $encrypted_e7ac0b1660ba_iv -in android/app/release.keystore.enc -out android/app/release.keystore -d
- nvm install node
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npm test
- cd android && ./gradlew assembleRelease
cache:
  directories:
  - node_modules
env:
  global:
    secure: rjWIyCT8TiENJX/pLiR21iOWpF3pGC29wVeZfiunnY3WRx19M0U4Gaj+2nmve5pWPK9qBLWeoXuJ9yh75U9sXSxFvz0IOiuPXOP9gPvH29AiYp71HXIUX/IMTD7/y4/H0EQ4Cl+lESrkvSaId3AVS8L1jEbfnOe3dZaLIAr5/81eoGK49h2rb60iXqzZsma1OWQn2xkMOAohYu9Wk9nURM5TVY+lEvqm4xFZRo042xQoTAtEOaEOdlXa2ETWuiTt19MlCmfIsojQMAON/8E8bsjJC5WpSmZTWwVykwOg8o/M134DxN8YOo0KmkUvpZxnfJ5B30th5i3NmXzx6+735lIS++PdTm6kYWpnfIE83wq/qrcsB5fbZrHUt8jtVrcoimQ+GTZxNGPJzG84NY8KtMAh3Wv2/gI2B/G2gkObiEI0Bof45Qoon3L93v6qXYvUgEHKF4umUHUh48MkAw4mqIEVf6ot++1ac+gmkYHZiys6SAKBeZZO4LOvpFrpwprTm6l+hFOgHphknh6QCn07W7VtbhyJjmaPbIxEFI03/RntOpd5ieTNQg4SGHMKKLUkUlpmtWteDH4iyN4t1Tr9y3rcrbicNirEUIR0voLtfPZyGY15zakaHzsI6/chFNiZpocHjdcR0oBGySZYWELwr+eO6dOxU+IzW9Z+yUv14uQ=
